"""Add Plaid integration: connected_accounts table and extend assets/liabilities

Revision ID: 8cc070c9fc07
Revises: 
Create Date: 2025-12-29 05:17:35.173882+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc070c9fc07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plaid_item_id', sa.String(length=255), nullable=False),
    sa.Column('plaid_access_token', sa.Text(), nullable=False),
    sa.Column('plaid_account_id', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connected_accounts_plaid_account_id'), 'connected_accounts', ['plaid_account_id'], unique=True)
    op.create_index(op.f('ix_connected_accounts_plaid_item_id'), 'connected_accounts', ['plaid_item_id'], unique=True)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.add_column('assets', sa.Column('connected_account_id', sa.String(length=36), nullable=True))
    op.add_column('assets', sa.Column('is_connected', sa.Boolean(), nullable=False))
    op.add_column('assets', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_assets_user_id', table_name='assets')
    op.create_index(op.f('ix_assets_connected_account_id'), 'assets', ['connected_account_id'], unique=False)
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    op.add_column('liabilities', sa.Column('connected_account_id', sa.String(length=36), nullable=True))
    op.add_column('liabilities', sa.Column('is_connected', sa.Boolean(), nullable=False))
    op.add_column('liabilities', sa.Column('last_synced_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_liabilities_user_id', table_name='liabilities')
    op.create_index(op.f('ix_liabilities_connected_account_id'), 'liabilities', ['connected_account_id'], unique=False)
    op.create_index(op.f('ix_liabilities_user_id'), 'liabilities', ['user_id'], unique=False)
    op.drop_index('idx_onboarding_state_user_id', table_name='onboarding_state')
    op.drop_index('idx_onboarding_state_user_id_unique', table_name='onboarding_state')
    op.create_index(op.f('ix_onboarding_state_user_id'), 'onboarding_state', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onboarding_state_user_id'), table_name='onboarding_state')
    op.create_index('idx_onboarding_state_user_id_unique', 'onboarding_state', ['user_id'], unique=True)
    op.create_index('idx_onboarding_state_user_id', 'onboarding_state', ['user_id'], unique=False)
    op.drop_index(op.f('ix_liabilities_user_id'), table_name='liabilities')
    op.drop_index(op.f('ix_liabilities_connected_account_id'), table_name='liabilities')
    op.create_index('idx_liabilities_user_id', 'liabilities', ['user_id'], unique=False)
    op.drop_column('liabilities', 'last_synced_at')
    op.drop_column('liabilities', 'is_connected')
    op.drop_column('liabilities', 'connected_account_id')
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_connected_account_id'), table_name='assets')
    op.create_index('idx_assets_user_id', 'assets', ['user_id'], unique=False)
    op.drop_column('assets', 'last_synced_at')
    op.drop_column('assets', 'is_connected')
    op.drop_column('assets', 'connected_account_id')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_plaid_item_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_plaid_account_id'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###

